/**
 * SEO AI Generation — Types
 * Types for the AI-powered SEO optimization system
 */

import { Timestamp } from 'firebase-admin/firestore';

/** Supported site locales for SEO generation */
export const SITE_LOCALES = ['fr', 'en', 'es', 'de', 'pt', 'ru', 'zh', 'ar', 'hi'] as const;
export type SiteLocale = typeof SITE_LOCALES[number];

/** Single FAQ item */
export interface SEOFaqItem {
  question: string;
  answer: string;
}

/** Structured data fields generated by AI */
export interface SEOStructuredData {
  knowsAbout: string[];
  serviceDescription: string;
}

/** SEO data for a single locale */
export interface SEOLocaleData {
  metaTitle: string;
  metaDescription: string;
  faqs: SEOFaqItem[];
  ogTitle: string;
  ogDescription: string;
  aiSummary: string;
  aiKeyFacts: string[];
  profileDescription: string;
  breadcrumbLabel: string;
  structuredData: SEOStructuredData;
}

/** Original description analysis (language-independent, done once) */
export interface SEOOriginalDescription {
  corrected: string | null;
  detectedLanguage: string;
  qualityScore: number;
  correctionsMade: string[];
}

/** Full SEO document stored in Firestore: seo_optimized/{providerId} */
export interface SEOOptimizedDoc {
  locales: Partial<Record<SiteLocale, SEOLocaleData>>;
  originalDescription: SEOOriginalDescription;
  metadata: {
    generatedAt: Timestamp;
    modelUsed: string;
    inputHash: string;
    version: number;
  };
}

/** Input data extracted from sos_profiles for the Claude prompt */
export interface SEOGenerationInput {
  uid: string;
  type: 'lawyer' | 'expat';
  firstName: string;
  lastName: string;
  country: string;
  countryName: string;
  city?: string;
  languages: string[];
  specialtiesLabels: string[];
  yearsOfExperience?: number;
  yearsAsExpat?: number;
  rating?: number;
  reviewCount?: number;
  totalCalls?: number;
  description?: string;
  price: string;
  profileUrl: string;
}

/** Claude API response parsed from JSON */
export interface ClaudeLocaleResponse {
  metaTitle?: string;
  metaDescription?: string;
  faqs?: { question?: string; answer?: string }[];
  ogTitle?: string;
  ogDescription?: string;
  aiSummary?: string;
  aiKeyFacts?: string[];
  profileDescription?: string;
  breadcrumbLabel?: string;
  structuredData?: {
    knowsAbout?: string[];
    serviceDescription?: string;
  };
}

/** Claude analysis response for description correction */
export interface ClaudeAnalysisResponse {
  detectedLanguage?: string;
  corrected?: string;
  qualityScore?: number;
  correctionsMade?: string[];
}
