/**
 * AiResponseDisplay - Affichage de la réponse IA générée
 *
 * Affiche la réponse IA avec badge auto-généré et actions
 */

import React, { useState } from 'react';
import { Bot, Copy, Check, Clock, Sparkles, ExternalLink } from 'lucide-react';
import type { AiResponse } from '../../hooks/useMultiProviderDashboard';
import { cn } from '../../utils/cn';

interface AiResponseDisplayProps {
  aiResponse: AiResponse;
  bookingId: string;
}

const AiResponseDisplay: React.FC<AiResponseDisplayProps> = ({
  aiResponse,
  bookingId,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(aiResponse.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const formatDate = (date: Date) => {
    return new Intl.DateTimeFormat('fr-FR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(date);
  };

  const isAutoGenerated = aiResponse.source === 'multi_dashboard_auto';

  return (
    <div className="mt-3 bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 rounded-xl border border-blue-200 dark:border-blue-800 overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2 bg-white/50 dark:bg-gray-800/50 border-b border-blue-200 dark:border-blue-800">
        <div className="flex items-center gap-2">
          <Bot className="w-4 h-4 text-blue-600 dark:text-blue-400" />
          <span className="text-sm font-medium text-blue-900 dark:text-blue-200">
            Réponse IA
          </span>
          {isAutoGenerated && (
            <span className="flex items-center gap-1 px-2 py-0.5 bg-gradient-to-r from-purple-500 to-blue-500 text-white text-[10px] font-semibold rounded-full">
              <Sparkles className="w-2.5 h-2.5" />
              Auto-généré
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          {/* Copy Button */}
          <button
            onClick={handleCopy}
            className={cn(
              "flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-medium transition-all",
              copied
                ? "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400"
                : "bg-white dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-600"
            )}
            title="Copier la réponse"
          >
            {copied ? (
              <>
                <Check className="w-3 h-3" />
                Copié
              </>
            ) : (
              <>
                <Copy className="w-3 h-3" />
                Copier
              </>
            )}
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="p-4">
        <p className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap leading-relaxed">
          {aiResponse.content}
        </p>
      </div>

      {/* Footer */}
      <div className="px-4 py-2 bg-white/30 dark:bg-gray-800/30 border-t border-blue-100 dark:border-blue-800/50 flex items-center justify-between text-xs text-gray-500 dark:text-gray-400">
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-1">
            <Clock className="w-3 h-3" />
            {formatDate(aiResponse.generatedAt)}
          </span>
          <span className="text-gray-300 dark:text-gray-600">|</span>
          <span className="font-mono text-[10px] bg-gray-100 dark:bg-gray-700 px-1.5 py-0.5 rounded">
            {aiResponse.model}
          </span>
          {aiResponse.tokensUsed && (
            <>
              <span className="text-gray-300 dark:text-gray-600">|</span>
              <span>{aiResponse.tokensUsed} tokens</span>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default AiResponseDisplay;
