name: sos-expat
region: fra
static_sites:
  - name: sos-expat-frontend
    source_dir: /sos
    build_command: npm run build
    output_dir: dist
    environment_slug: node-js
    catchall_document: index.html
    routes:
      - path: /
        preserve_path_prefix: true
    cors:
      allow_origins:
        - exact: https://sos-expat.com
        - exact: https://www.sos-expat.com
      allow_methods:
        - GET
        - HEAD
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
      max_age: "86400"
    headers:
      - path: /*
        values:
          - key: Strict-Transport-Security
            value: max-age=31536000; includeSubDomains; preload
          - key: X-Content-Type-Options
            value: nosniff
          - key: X-Frame-Options
            value: SAMEORIGIN
          - key: Referrer-Policy
            value: strict-origin-when-cross-origin
          - key: Permissions-Policy
            value: camera=(), microphone=(self), geolocation=(self)
      - path: /assets/*
        values:
          - key: Cache-Control
            value: public, max-age=31536000, immutable
      - path: /*.js
        values:
          - key: Cache-Control
            value: public, max-age=31536000, immutable
      - path: /*.css
        values:
          - key: Cache-Control
            value: public, max-age=31536000, immutable
      - path: /*.woff2
        values:
          - key: Cache-Control
            value: public, max-age=31536000, immutable
      - path: /icons/*
        values:
          - key: Cache-Control
            value: public, max-age=604800
