{
  "name": "sos-expats-admin",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "description": "Plateforme d'administration SOS Expats avec intégration ChatGPT sécurisée",
  "author": "Votre Nom <email@example.com>",
  "license": "UNLICENSED",
  "keywords": ["react", "typescript", "firebase", "admin", "pwa"],
  "scripts": {
    "dev": "vite --host",
    "build": "npm run type-check && vite build && npm run build:functions",
    "build:functions": "cd functions && npm run build",
    "build:analyze": "npm run build && npx vite-bundle-analyzer dist/stats.html",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "lint:fix": "eslint . --ext ts,tsx --fix",
    "format": "prettier --write \"src/**/*.{ts,tsx,js,jsx,json,css,md}\"",
    "format:check": "prettier --check \"src/**/*.{ts,tsx,js,jsx,json,css,md}\"",
    "preview": "vite preview --host",
    "type-check": "tsc --noEmit",
    "type-check:watch": "tsc --noEmit --watch",
    "test": "vitest",
    "test:coverage": "vitest --coverage",
    "deploy": "npm run build && firebase deploy",
    "clean": "rm -rf dist node_modules/.vite"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.28.0",
    "firebase": "^10.14.1",
    "date-fns": "^4.1.0",
    "lucide-react": "^0.454.0",
    "react-hook-form": "^7.53.2",
    "@hookform/resolvers": "^3.10.0",
    "zod": "^3.23.8",
    "react-hot-toast": "^2.4.1",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.5.4",
    "workbox-window": "^7.1.0",
    "@tanstack/react-query": "^5.59.0",
    "react-error-boundary": "^4.1.2"
  },
  "devDependencies": {
    "@types/node": "^22.8.1",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react-swc": "^3.7.1",
    "@typescript-eslint/eslint-plugin": "^8.11.0",
    "@typescript-eslint/parser": "^8.11.0",
    "eslint": "^8.57.1",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.14",
    "eslint-plugin-jsx-a11y": "^6.10.2",
    "eslint-plugin-import": "^2.31.0",
    "globals": "^15.11.0",
    "typescript": "^5.6.3",
    "vite": "^5.4.10",
    "vite-plugin-pwa": "^0.20.5",
    "vite-plugin-checker": "^0.8.0",
    "tailwindcss": "^3.4.14",
    "postcss": "^8.4.47",
    "autoprefixer": "^10.4.20",
    "rollup-plugin-visualizer": "^5.12.0",
    "firebase-tools": "^13.22.0",
    "@tailwindcss/forms": "^0.5.9",
    "tailwindcss-animate": "^1.0.7",
    "vitest": "^2.1.3",
    "@testing-library/react": "^16.0.1",
    "@testing-library/jest-dom": "^6.6.3",
    "jsdom": "^25.0.1",
    "prettier": "^3.3.3"
  },
  "engines": {
    "node": ">=18.0.0",
    "npm": ">=9.0.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 2 chrome version",
      "last 2 firefox version",
      "last 2 safari version"
    ]
  }
}{
  "name": "sos-expats-admin",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "description": "Plateforme d'administration SOS Expats avec intégration ChatGPT sécurisée",
  "author": "Votre Nom <email@example.com>",
  "license": "UNLICENSED",
  "keywords": ["react", "typescript", "firebase", "admin", "pwa"],
  "scripts": {
    "dev": "vite --host",
    "build": "npm run type-check && vite build && npm run build:functions",
    "build:functions": "cd functions && npm run build",
    "build:analyze": "npm run build && npx vite-bundle-analyzer dist/stats.html",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "lint:fix": "eslint . --ext ts,tsx --fix",
    "format": "prettier --write \"src/**/*.{ts,tsx,js,jsx,json,css,md}\"",
    "format:check": "prettier --check \"src/**/*.{ts,tsx,js,jsx,json,css,md}\"",
    "preview": "vite preview --host",
    "type-check": "tsc --noEmit",
    "type-check:watch": "tsc --noEmit --watch",
    "test": "vitest",
    "test:coverage": "vitest --coverage",
    "deploy": "npm run build && firebase deploy",
    "clean": "rm -rf dist node_modules/.vite"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.28.0",
    "firebase": "^10.14.1",
    "date-fns": "^4.1.0",
    "lucide-react": "^0.454.0",
    "react-hook-form": "^7.53.2",
    "@hookform/resolvers": "^3.10.0",
    "zod": "^3.23.8",
    "react-hot-toast": "^2.4.1",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.5.4",
    "workbox-window": "^7.1.0",
    "@tanstack/react-query": "^5.59.0",
    "react-error-boundary": "^4.1.2"
  },
  "devDependencies": {
    "@types/node": "^22.8.1",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react-swc": "^3.7.1",
    "@typescript-eslint/eslint-plugin": "^8.11.0",
    "@typescript-eslint/parser": "^8.11.0",
    "eslint": "^8.57.1",
    "eslint-plugin-react-hooks": "^4.6.2",
    "eslint-plugin-react-refresh": "^0.4.14",
    "eslint-plugin-jsx-a11y": "^6.10.2",
    "eslint-plugin-import": "^2.31.0",
    "globals": "^15.11.0",
    "typescript": "^5.6.3",
    "vite": "^5.4.10",
    "vite-plugin-pwa": "^0.20.5",
    "vite-plugin-checker": "^0.8.0",
    "tailwindcss": "^3.4.14",
    "postcss": "^8.4.47",
    "autoprefixer": "^10.4.20",
    "rollup-plugin-visualizer": "^5.12.0",
    "firebase-tools": "^13.22.0",
    "@tailwindcss/forms": "^0.5.9",
    "tailwindcss-animate": "^1.0.7",
    "vitest": "^2.1.3",
    "@testing-library/react": "^16.0.1",
    "@testing-library/jest-dom": "^6.6.3",
    "jsdom": "^25.0.1",
    "prettier": "^3.3.3"
  },
  "engines": {
    "node": ">=18.0.0",
    "npm": ">=9.0.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 2 chrome version",
      "last 2 firefox version",
      "last 2 safari version"
    ]
  }
}