#!/bin/bash

# Script de suppression des anciennes fonctions d'affiliation en europe-west1
# Ces fonctions vont être redéployées en europe-west2

echo "🗑️  Suppression des anciennes fonctions d'affiliation en europe-west1..."
echo ""

# Liste des fonctions à supprimer (générée par Firebase)
FUNCTIONS=(
  "adminAdvanceCycle"
  "adminCreateBloggerArticle"
  "adminCreateBloggerGuideBestPractice"
  "adminCreateBloggerGuideCopyText"
  "adminCreateBloggerGuideTemplate"
  "adminCreateBloggerResource"
  "adminCreateBloggerResourceText"
  "adminCreateChatterTrainingModule"
  "adminCreateGroupAdminPost"
  "adminCreateGroupAdminResource"
  "adminCreateInfluencerResource"
  "adminCreateInfluencerResourceText"
  "adminCreateInfluencerTrainingModule"
  "adminDeleteBloggerArticle"
  "adminDeleteBloggerResource"
  "adminDeleteChatterTrainingModule"
  "adminDeleteGroupAdminPost"
  "adminDeleteGroupAdminResource"
  "adminDeleteInfluencerResource"
  "adminDeleteInfluencerResourceText"
  "adminDeleteInfluencerTrainingModule"
  "adminExportBloggers"
  "adminExportGroupAdmins"
  "adminGetBloggerArticles"
  "adminGetBloggerConfig"
  "adminGetBloggerDetail"
  "adminGetBloggerLeaderboard"
  "adminGetBloggersList"
  "adminGetChatterTrainingModules"
  "adminGetGroupAdminConfig"
  "adminGetGroupAdminDetail"
  "adminGetGroupAdminPostsList"
  "adminGetGroupAdminRecruits"
  "adminGetGroupAdminResourcesList"
  "adminGetGroupAdminWithdrawalsList"
  "adminGetGroupAdminsList"
  "adminGetGroups"
  "adminGetInfluencerConfig"
  "adminGetInfluencerDetail"
  "adminGetInfluencerLeaderboard"
  "adminGetInfluencerResources"
  "adminGetInfluencerTrainingModules"
  "adminGetInfluencersList"
  "adminGetPendingInfluencerWithdrawals"
  "adminGetRecruitmentsList"
  "adminProcessBloggerWithdrawal"
  "adminProcessGroupAdminWithdrawal"
  "adminProcessInfluencerWithdrawal"
  "adminReorderChatterTrainingModules"
  "adminUpdateBloggerArticle"
  "adminUpdateBloggerConfig"
  "adminUpdateBloggerGuideBestPractice"
  "adminUpdateBloggerGuideCopyText"
  "adminUpdateBloggerGuideTemplate"
  "adminUpdateBloggerResource"
  "adminUpdateBloggerStatus"
  "adminUpdateChatterTrainingModule"
  "adminUpdateCycleThreshold"
  "adminUpdateGroupAdminConfig"
  "adminUpdateGroupAdminPost"
  "adminUpdateGroupAdminResource"
  "adminUpdateGroupAdminStatus"
  "adminUpdateGroupStatus"
  "adminUpdateInfluencerConfig"
  "adminUpdateInfluencerResource"
  "adminUpdateInfluencerResourceText"
  "adminUpdateInfluencerStatus"
  "adminUpdateInfluencerTrainingModule"
  "adminVerifyGroup"
  "bloggerRequestWithdrawal"
  "chatterRequestWithdrawal"
  "copyBloggerArticle"
  "copyBloggerGuideText"
  "copyBloggerResourceText"
  "copyInfluencerResourceText"
  "downloadBloggerResource"
  "downloadInfluencerResource"
  "getAvailableGroups"
  "getBloggerArticles"
  "getBloggerDashboard"
  "getBloggerGuide"
  "getBloggerLeaderboard"
  "getBloggerResources"
  "getChatterDashboard"
  "getChatterLeaderboard"
  "getGroupAdminCommissions"
  "getGroupAdminDashboard"
  "getGroupAdminLeaderboard"
  "getGroupAdminNotifications"
  "getGroupAdminPostContent"
  "getGroupAdminPosts"
  "getGroupAdminProcessedPost"
  "getGroupAdminProcessedResourceContent"
  "getGroupAdminResourceContent"
  "getGroupAdminResources"
  "getInfluencerDashboard"
  "getInfluencerLeaderboard"
  "getInfluencerResources"
  "getInfluencerTrainingCertificate"
  "getInfluencerTrainingModuleContent"
  "getInfluencerTrainingModules"
  "getMyGroups"
  "getReferralDashboard"
  "influencerRequestWithdrawal"
  "joinGroupAsChatter"
  "registerBlogger"
  "registerChatter"
  "registerGroupAdmin"
  "registerInfluencer"
  "requestGroupAdminWithdrawal"
  "resetChatterConfigToDefaults"
  "submitGroup"
  "submitInfluencerTrainingQuiz"
  "trackBloggerGuideUsage"
  "trackGroupAdminPostUsage"
  "trackGroupAdminResourceUsage"
  "updateBloggerProfile"
  "updateChatterProfile"
  "updateGroupAdminProfile"
  "updateInfluencerProfile"
  "updateInfluencerTrainingProgress"
)

TOTAL=${#FUNCTIONS[@]}
CURRENT=0
FAILED=0

for func in "${FUNCTIONS[@]}"; do
  CURRENT=$((CURRENT + 1))
  echo "[$CURRENT/$TOTAL] Suppression de $func..."

  if firebase functions:delete "$func" --region europe-west1 --project sos-urgently-ac307 --force 2>&1 | grep -q "successfully deleted\|does not exist"; then
    echo "  ✅ Supprimé"
  else
    echo "  ⚠️  Échec (peut-être déjà supprimé)"
    FAILED=$((FAILED + 1))
  fi
done

echo ""
echo "✨ Suppression terminée !"
echo "   Succès: $((TOTAL - FAILED))/$TOTAL"
if [ $FAILED -gt 0 ]; then
  echo "   Échecs: $FAILED (probablement déjà supprimés)"
fi
echo ""
echo "🚀 Vous pouvez maintenant redéployer avec:"
echo "   firebase deploy --only functions --project=sos-urgently-ac307"
